# Generated by Django 5.1.6 on 2025-03-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aperd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pic', models.CharField(max_length=500)),
                ('progress', models.CharField(choices=[('On Board', 'On Board'), ('OPS Memo', 'OPS Memo'), ('MPD', 'MPD'), ('Next Action', 'Next Action'), ('PKS', 'PKS'), ('PKS 2', 'PKS 2'), ('Resiprokal Transaksi', 'Resiprokal Transaksi')], default=None, max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
